[template]
name = "create-tauri-mobile-cli"
description = "A Tauri + xterm.js CLI template"
include = ["src-tauri/tauri.conf.json", "src-tauri/Cargo.toml"]

[placeholders.identifier]
type = "string"
prompt = "App Identifier (e.g. com.google.camera)"
default = "com.{{ env USER | env USERNAME | default `example` }}"
