[template]
name = "create-tauri-mobile-cli"
description = "A Tauri + xterm.js CLI template"
include = [
  "src-tauri/tauri.conf.json",
  "src-tauri/Cargo.toml",
  "cargo-generate.toml",
]

[placeholders.identifier]
type = "string"
prompt = "App Identifier (e.g. com.google.camera)"
default = "com.example.{{project-name}}"
